### ISSUE TITLE
끄투 문의드려요~

### ISSUE THREAD

**Issue by KORraimi** [pkpai0926/KKuTu#1]
끄투 운영하시는거 보고 문의드립니다~
in_kkutu~.js 계열이 없어서 진행이 안되는데 어떡게 해결하나요?

**Comment by BasixKOR** [comment]
그게 정확히 어떤 파일인가요?

**Comment by KORraimi** [comment]
불러오는중...앞으로 1 오류 수정 어예하나요?

**Comment by pkpai0926** [comment]
파일이 어떤 상태인지, 서버가 어떤 상태인지 모든 것을 정확히 알려주셔야 해결이 가능합니다. 일단 어디서 오류났는지 보게 브라우저 켜고 F12 켜고 뜨는 사진 캡처해서 사진 올려주세요.
